version: '2'
services:
  loadbalancer:
    image: rancher/lb-service-haproxy:v0.7.5
    expose:
      - 8000:8000/tcp
      - 8001:8001/tcp
      - 8002:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  kong-database:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: kong
      POSTGRES_USER: kong
    stdin_open: true
    tty: true
    volumes_from:
      - kong-data
    labels:
      io.rancher.sidekicks: kong-data
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  kong-dashboard:
    image: pgbi/kong-dashboard:latest
    tty: true
    links:
      - kong:kong
    # ports:
    #   - 8080:8080/tcp
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  kong-data:
    image: busybox
    volumes:
      - /var/lib/postgresql/data/pgdata
    labels:
      io.rancher.container.start_once: 'true'
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    tty: true
    links:
      - kong-database:kong-database
    # ports:
    #   - 7946:7946/tcp
    #   - 7946:7946/udp
    #   - 8000:8000/tcp
    #   - 8001:8001/tcp
    #   - 8443:8443/tcp
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
