kong-data:
  image: busybox
  labels:
    io.rancher.container.start_once: true
  volumes:
    - /var/lib/postgresql/data/pgdata
kong-database:
  image: postgres:latest
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: ${postgres_db}
    POSTGRES_USER: ${postgres_user}
    POSTGRES_PASSWORD: ${postgres_password}
  tty: true
  stdin_open: true
  labels:
    io.rancher.sidekicks: kong-data
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - kong-data
kong:
  image: kong:latest
  ports:
  - 7946:7946/tcp
  - 7946:7946/udp
  - 8000:8000/tcp
  - 8001:8001/tcp
  - 8443:8443/tcp
  environment:
    POSTGRES_HOST: ${postgres_db}
    POSTGRES_PORT: 5432
    POSTGRES_DB: kongdb
    POSTGRES_USER: ${postgres_user}
    POSTGRES_PASSWORD: ${postgres_password}
  links:
    - kong-database:kong-database
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
kong-dashboard:
  image: pgbi/kong-dashboard:v2
  ports:
    - 8080:8080
  links:
    - kong
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
